version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  springboot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/test
      STRAVA_CLIENT_SECRET: ${STRAVA_CLIENT_SECRET}
      # Other environment variables for MongoDB configuration if necessary

volumes:
  mongodb_data:
