version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  springboot:
    image: mackfitness-web-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/test
      STRAVA_CLIENT_SECRET: ${STRAVA_CLIENT_SECRET}

  react-ui:
    image: mackfitness-ui:latest
    build:
      context: ./mackfitness-ui/
      dockerfile: Dockerfile.dev
    volumes:
      - ~Projects/MackFitness/mackfitness-ui/:/app
#    environment:
#      - MACKFITNESS_WEB_SERVER_API_URL=http://localhost:8080
    ports:
      - "3000:3000"

volumes:
  mongodb_data:
